version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm run start

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: vpnuser
      POSTGRES_PASSWORD: vpnpassword
      POSTGRES_DB: vpndb
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  pgdata:
